// <auto-generated />
namespace WritersBlock.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FixComments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixComments));
        
        string IMigrationMetadata.Id
        {
            get { return "202101272302370_Fix Comments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
